# Generated by Django 4.0.5 on 2022-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_order_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_now_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('security_code', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('deliveryOrderId', models.FloatField()),
                ('deliveryURL', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='buyNow_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('security_code', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('deliveryOrderId', models.FloatField()),
                ('deliveryURL', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='order_details',
        ),
    ]
