# Generated by Django 4.0.5 on 2022-07-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_order_info_delete_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_detail',
        ),
    ]
