# Generated by Django 4.0.5 on 2022-08-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_new_order_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_order_info',
        ),
    ]
