# Generated by Django 4.0.5 on 2022-08-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_neww_order_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_order_info',
        ),
    ]
