# Generated by Django 4.1 on 2022-09-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_order_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_charges',
            name='charge_per_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='additional_charges',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='additional_charges',
            name='scheme_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='additional_charges',
            name='scheme_type',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_rate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='delivery_rate',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('CANADA', 'CANADA')], default='USA', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_rate',
            name='delivery_type',
            field=models.CharField(choices=[('DOX', 'DOX'), ('WPX', 'WPX')], default='WPX', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_rate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery_rate',
            name='weight',
            field=models.DecimalField(choices=[('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2')], decimal_places=2, default='0.5', max_digits=20),
        ),
        migrations.AlterModelTable(
            name='additional_charges',
            table='delivery_additional_charges',
        ),
        migrations.AlterModelTable(
            name='delivery_rate',
            table='delivery_delivery_rate',
        ),
    ]
